---
- hosts: localhost
  gather_facts: no
  connection: local
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  vars:
    db: true
    ui: false
    wk: false
  roles:
    - {role: 'roles/jritenour.ec2-cf-miq'}

- hosts: cfdb
  remote_user: ec2-user
  gather_facts: no
  become: true
  tasks: 
    - name:
      command: "sudo sed -i 's/^.*ssh-rsa/ssh-rsa/p' /root/.ssh/authorized_keys"

- hosts: cfdb
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-db'}
  tasks:
  - name: Wait for CloudForms services to come up
    wait_for:
      host: "{{ hostvars[groups['cfdb'][0]]['ansible_default_ipv4']['address'] }}"
      port: "443"
      delay: "120"
      timeout: "600"
      state: "started"

  - name: Additional wait for API to become responsive
    pause:
      minutes: 1

  - name: Add host platform as provider
    uri:
      url: "https://{{ hostvars[groups['cfdb'][0]]['ansible_default_ipv4']['address'] }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Amazon::CloudManager"
        name:  Amazon EC2
        provider_region: "{{ az }}"
        credentials:
          userid: "{{ ec2_access_key }}"
          password: "{{ ec2_secret_key }}"

  - name: Download automate file
    get_url:
      url: https://raw.githubusercontent.com/jritenour/cf-poc/master/automate/datastore.zip
      dest: /root/datastore.zip
      mode: 0644
  - name: Import automate domain
    command: '/var/www/miq/vmdb/bin/rake evm:automate:import DOMAIN=POC ZIP_FILE=/root/datastore.zip PREVIEW=false ENABLED=true'
    args:
      chdir: /var/www/miq/vmdb
  - name: Download dialog file
    get_url:
      url: https://raw.githubusercontent.com/jritenour/cf-poc/master/dialogs/dialog.yml
      dest: /root/dialog.yml
      mode: 0644
  - name: Import service dialogs
    command: "/var/www/miq/vmdb/bin/rake dialogs:import['/root/dialog.yml']"
    args:
      chdir: /var/www/miq/vmdb
