---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: wk
    db: false
    ui: false
    wk: true
    float_ip: "{{ wk_server }}"
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'roles/jritenour.osp-cf-miq'}

- hosts: cfwk
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    zone_name: OpenStack
    zone_desc: OpenStack Zone
    float_ip: "{{ wk_server }}"
  roles: 
    - {role: 'roles/jritenour.cf-miq-wk'}
