---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: wk
    db: false
    ui: false
    wk: true
    num: 
     - 1
     - 2
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'roles/jritenour.osp-cf-miq'}

- hosts: cfwk
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    zone_name: OpenStack
    zone_desc: OpenStack Zone
    db_server: "{{ hostvars[groups['cfdb'][0]]['ansible_default_ipv4']['address'] }}"
  roles: 
    - {role: 'roles/jritenour.cf-miq-wk'}

  tasks:
  - name: Add host platform as provider
    uri:
      url: "https://{{ db_server }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Openstack::CloudManager"
        name:  OSP
        hostname: "{{ osp_ip }}"
        ipaddress: "{{ osp_ip }}"
        port: "5000"
        security_protocol: "non_ssl"
        credentials:
          userid: "{{ osp_user }}"
          password: "{{ osp_pass }}"
