---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    type: db
    db: true
    ui: false
    wk: false
    num: 1
  roles:
    - {role: 'roles/jritenour.osp-cf-miq'}

- hosts: cfdb
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    zone_name: DB
    zone_desc: Database zone
    db_server: "{{ hostvars[groups['cfdb'][0]]['ansible_default_ipv4']['address'] }}"
  roles: 
    - {role: 'roles/jritenour.cf-miq-db'}
  tasks:
  - name: Add host platform as provider
    uri:
      url: "https://{{ db_server }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Openstack::CloudManager"
        name:  OSP
        hostname: "{{ osp_ip }}"
        ipaddress: "{{ osp_ip }}"
        port: "5000"
        security_protocol: "non_ssl"
        credentials:
          userid: "{{ osp_user }}"
          password: "{{ osp_pass }}"
