---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles:
    - {role: 'roles/jritenour.rhv-cf-miq'}
  tasks:
  - name: Wait for CloudForms services to come up
    wait_for:
      host: "{{ ipaddr }}"
      port: "22"
      delay: "30"
      timeout: "300"
      state: "started"

- hosts: cfdb
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-db'}
  tasks:
  - name: Wait for CloudForms services to come up
    wait_for:
      host: "{{ ipaddr }}"
      port: "443"
      delay: "120"
      timeout: "600"
      state: "started"

  - name: Additional wait for API to become responive
    pause:
      minutes: 1

  - name: Add host platform as provider
    uri:
      url: "https://{{ ansible_eth0.ipv4.address }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Redhat::InfraManager"
        name:  RHVM
        hostname: "{{ rhvm_addr }}"
        ipaddress: 192.168.2.26
        verify_ssl: 0
        credentials:
          userid: "admin@internal"
          password: "{{ rhv_pass }}"
