---
- hosts: cfdb
  remote_user: root
  vars_files:
    - '../main.yml'
  tasks:
  - name: Add undercloud as provider
    uri:
      url: "https://{{ db_server }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Openstack::InfraManager"
        name:  OSP Undercloud 2
        hostname: "{{ undercloud_ip }}"
        ipaddress: "{{ undercloud_ip }}"
        port: "13000"
        security_protocol: "non_ssl"
        credentials:
          userid: "{{ undercloud_user }}"
          password: "{{ undercloud_pw }}"
