---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: wk
    db: false
    ui: false
    wk: true
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles:
    - {role: 'roles/jritenour.vmware-cf-miq'}

- hosts: cfwk
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-wk'}
