---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: wk
    db: false
    ui: false
    wk: true
    ip_addr: "{{ wk_server }}"
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'roles/jritenour.vmware-cf-miq'}

- hosts: cfwk
  remote_user: root

  vars:
    zone_name: VMware
    zone_desc: VMware Worker Zone

  vars_files:
    - '../main.yml'

  roles: 
    - {role: 'roles/jritenour.cf-miq-wk'}

  tasks:
  - name: Copy VDDK to appliance
    copy:
      src: /staging/VMware-vix-disklib-6.0.0-2498720.x86_64.tar.gz
      dest: /root/VMware-vix-disklib-6.0.0-2498720.x86_64.tar.gz

  - name: Extract VDDK archive
    unarchive:
      src: /root/VMware-vix-disklib-6.0.0-2498720.x86_64.tar.gz
      dest: /usr/lib/
      remote_src: yes

  - name: move the vmware-vix dir
    command: 'mv /usr/lib/vmware-vix-disklib-distrib  /usr/lib/vmware-vix-disklib'

  - name: Link libvixDiskLib.so
    file:
      src: /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so
      dest: /usr/lib/libvixDiskLib.so
      state: link

  - name: Link libvixDiskLib.so.6
    file:
      src: /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so.6
      dest: /usr/lib/libvixDiskLib.so.6
      state: link

  - name: Run ldconfig
    command: 'ldconfig'
