---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    type: db
    db: true
    ui: false
    wk: false
    ip_addr: "{{ db_server }}"
  roles:
    - {role: 'roles/jritenour.vmware-cf-miq'}

- hosts: cfdb
  remote_user: root
  vars:
    zone_name: DB
    zone_desc: Database zone
  vars_files:
    - '../main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-db'}
  tasks:

  - name: Add host platform as provider
    uri:
      url: "https://{{ db_server }}/api/providers"
      method: POST
      user: admin
      password: "{{ cf_ssh_pass }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        type: "ManageIQ::Providers::Vmware::InfraManager"
        name:  VMware
        hostname: "{{ vcenter_ip }}"
        ipaddress: "{{ vcenter_ip }}"
        credentials:
          userid: "{{ vcenter_user }}"
          password: "{{ vcenter_pass }}"
