---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: ui
    db: false
    ui: true
    wk: false
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'roles/jritenour.vmware-cf-miq'}

- hosts: cfui
  remote_user: root
  vars:
    zone_name: UI
    zone_desc: UI Zone
  vars_files:
    - '../main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-ui'}
  tasks:
  - name: Create Zone
    shell: "/var/www/miq/vmdb/bin/rails runner 'Zone.create(:name => \"{{ zone_name }}\", :description => \"{{ zone_desc }}\")'"
#  - name: Move UI server to UI Zone
#    command: "/var/www/miq/vmdb/bin/rails runner 'MiqServer.my_server.set_config(:server => {:zone =>"})'"
