---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars: 
    type: ui
    db: false
    ui: true
    wk: false
    zone_name: UI
    zone_desc: UI Zone
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles:
    - {role: 'roles/jritenour.vmware-cf-miq'}

- hosts: cfui
  remote_user: root
  vars_files:
    - 'roles/jritenour.cf-variables/vars/main.yml'
  roles: 
    - {role: 'roles/jritenour.cf-miq-wk'}
  - name: Create Zone
    shell: "/var/www/miq/vmdb/bin/rails runner 'Zone.create(:name => \"{{ zone_name }}\", :description => \"{{ zone_desc }}\")'"
