---
# tasks file for jritenour.vmware-cf-miq
  - name: create the VM
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      esxi_hostname: "{{ esx_host }}"
      datacenter: "{{ vc_datacenter }}"
      name: "{{ vm_name }}"
      state: poweredon
      disk:
      - size_gb: 40
        type: thin
        datastore: "{{ vc_datastore }}"
      - size_gb: "{{ db_size }}"
        type: thin
        datastore: "{{ vc_datastore }}"
      template: "{{ template_name }}"
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy

  - name: Debugging instance info
    debug:
      var: deploy.instance.hw_eth0.ipaddresses[0]

  - name: add DB server to inventory
    add_host:
      hostname: "{{ deploy.instance.hw_eth0.ipaddresses[0] }}"
      ansible_user: root
      ansible_ssh_pass: "{{ cf_ssh_pass }}"
      groupname: cfdb
    when: db

  - name: add Worker to inventory
    add_host:
      hostname: "{{ deploy.instance.hw_eth0.ipaddresses[0] }}"
      ansible_user: root
      ansible_ssh_pass: "{{ cf_ssh_pass }}"
      groupname: cfwk
    when: wk

  - name: add UI server to inventory
    add_host:
      hostname: "{{ deploy.instance.hw_eth0.ipaddresses[0] }}"
      ansible_user: root
      ansible_ssh_pass: "{{ cf_ssh_pass }}"
      groupname: cfui
    when: ui
